In [1]:
import tensorflow as tf
print("Available devices:", tf.config.list_physical_devices())


Available devices: [PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [2]:
import tensorflow as tf

# Check GPU availability
print("Is GPU available:", tf.config.list_physical_devices('GPU'))

# Simple TensorFlow computation to test
with tf.device('/GPU:0'):
    a = tf.constant([1.0, 2.0, 3.0])
    b = tf.constant([4.0, 5.0, 6.0])
    result = a + b
    print("Result:", result)


Is GPU available: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Result: tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)


2024-11-29 16:52:32.420271: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4 Pro
2024-11-29 16:52:32.420294: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 48.00 GB
2024-11-29 16:52:32.420298: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 18.00 GB
2024-11-29 16:52:32.420331: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-11-29 16:52:32.420339: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [3]:
import tensorflow as tf
import time

# Large matrix multiplication
with tf.device('/GPU:0'):
    start = time.time()
    a = tf.random.normal([10000, 10000])
    b = tf.random.normal([10000, 10000])
    c = tf.matmul(a, b)
    print("Matrix multiplication result:", c)
    print("Time taken (s):", time.time() - start)


Matrix multiplication result: tf.Tensor(
[[-3.5105759e+01 -7.3037552e+01 -6.9209099e+01 ... -4.9408108e+01
  -2.8063578e+01  1.8648810e+02]
 [-9.4072418e+01 -8.9466179e+01 -6.1277115e+01 ... -2.1704536e+02
   1.9599632e+02 -7.4192971e-01]
 [-1.3145932e+01  3.1350104e+02 -1.6003958e+02 ...  2.3898516e+01
  -9.0297562e+01  2.1194963e-01]
 ...
 [-1.2163195e+01 -7.2708076e-01  1.7865128e+02 ...  2.1823681e+01
  -7.8858459e+01  1.5708784e+02]
 [ 3.2431084e+01  6.8180031e+01 -1.8777891e+01 ... -1.9483902e+01
  -5.6429958e+01 -8.8283684e+01]
 [ 2.9451077e+01 -1.7146710e+02 -2.1852160e+01 ...  1.6869816e+01
  -7.4712837e+01  4.8941166e+01]], shape=(10000, 10000), dtype=float32)
Time taken (s): 0.5832540988922119


In [4]:
import tensorflow as tf
import time

# Large matrix multiplication
with tf.device('/CPU:0'):
    start = time.time()
    a = tf.random.normal([10000, 10000])
    b = tf.random.normal([10000, 10000])
    c = tf.matmul(a, b)
    print("Matrix multiplication result:", c)
    print("Time taken (s):", time.time() - start)


Matrix multiplication result: tf.Tensor(
[[ -77.14511    118.30941     47.141327  ...  -44.05091     85.056595
     9.875298 ]
 [  32.594387   -33.813595   121.2693    ...  -15.606556   126.811134
    41.652855 ]
 [  37.02806     10.174755   -71.04915   ...  -22.59147    -18.465773
  -129.16315  ]
 ...
 [ 102.680504   -59.684746    13.658905  ... -131.75647   -180.34067
   108.818085 ]
 [ 123.96       -70.51979     59.93358   ...  -43.23475     41.283386
    47.90332  ]
 [  17.737244    13.473427    10.657988  ...   99.271545     6.7223773
   113.87754  ]], shape=(10000, 10000), dtype=float32)
Time taken (s): 1.842047929763794
